# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

code_rabbit:
  language: ja

  review:
    enabled: true
    mode: incremental
    types:
      - code-quality
      - readability
      - performance
      - best-practices
      - security

  pull_request:
    summary: true
    inline_comments: true
    summary_mode: smart

  ignore:
    paths:
      - node_modules/
      - dist/
      - .next/
      - coverage/

  include:
    extensions:
      - .ts
      - .tsx
      - .js
      - .jsx
      - .py
      - .rb
