## 設定ドキュメント
## https://docs.coderabbit.ai/getting-started/configure-coderabbit/

## 対応するISO言語コードを使用して、レビューの言語を設定します。
language: "ja"

review:
  enabled: true
  mode: incremental  # incremental（差分）または full（全体レビュー）
  types:
    - code-quality
    - readability
    - performance
    - best-practices
    - security

pull_request:
  summary: true           # PR要約を表示
  inline_comments: true   # 行単位でのコメント表示
  summary_mode: smart     # 要約のモード（smart / simple）

ignore:
  paths:
    - node_modules/
    - dist/
    - .next/
    - coverage/

include:
  extensions:
    - .ts
    - .tsx
    - .js
    - .jsx
    - .py
    - .rb
